default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dev
  password: dev
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false
  timeout: 5000
  # socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: venjob_development
test:
  <<: *default
  database: venjob_test
production:
  <<: *default
  database: venjob_production
  username: venjob
  password: <%= ENV['VENJOB_DATABASE_PASSWORD'] %>